name: Check-Name-To-Commit Action

on:
    push:
      paths:
        - README.md
    pull_request:
      paths:
        - README.md
jobs:
    check-name-action:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
  
      - name: Check if README contains my name ('Alice' - case insensitive)
        run: |
          if ! grep -Ei "alice" README.md; then
            echo "Error: README.md does not contain the name 'Alice' - case insensitive."
            exit 1
          fi
  
      - name: Success Message
        run: echo "Ok, README.md contains the name 'Alice' - case insensitive."
